---
title: "STAT625_Project"
author: "Brian Zhang, Vi Mai, Xinyu Zhou (Anna), Ziyan Zhao"
date: "`r Sys.Date()`"
output: pdf_document
---
```{r}
library(ggplot2)
rm(list = ls())
walmart <- read.csv("Walmart.csv")
head(walmart)
```
```{r}
# Convert the dates from character strings into days since the first date 
asDate_result <- as.Date(walmart$Date, "%d-%m-%Y")
first_date <- min(asDate_result)
days_elapsed <- asDate_result-first_date
walmart["Days_since"] <- days_elapsed
head(walmart)
```
```{r}
# Comparing the need for a log transformation on Weekly Sales 
full_mod_no_log <- lm(Weekly_Sales ~ Days_since + Unemployment + CPI + Fuel_Price + Temperature + Holiday_Flag, data = walmart)
plot(full_mod_no_log,
     col = rgb(red = 0, green = 0, blue = 0, alpha = 0.25), 
     pch = 16
)

full_mod_w_log <- lm(log(Weekly_Sales) ~ Days_since + Unemployment + CPI + Fuel_Price + Temperature + Holiday_Flag, data = walmart)
plot(full_mod_w_log,
     col = rgb(red = 0, green = 0, blue = 0, alpha = 0.25), 
     pch = 16
)
```

```{r}
# Looking at effect of Days and Store on log(Weekly Sales)
plot(log(Weekly_Sales) ~ Days_since + Store + Temperature, data = walmart, 
     col = alpha(walmart$Store, 0.5),  # makes color dependent on store 
     pch = 16,
     cex = 0.6)
```